---
- name: Install Java (Windows)
  win_package:
    path: "{{ java_installers_path_on_target }}\\{{ java_installer_filename }}"
    creates_path: "{{ java_destination_path }}\\{{ java_type_and_version }}"
    state: present

- name: Get Installed Java Version
  win_command: "\"{{ java_destination_path }}\\{{ java_type_and_version }}\\bin\\java\" -version"
  register: java_version_result

- name: Java Version
  vars:
    msg: |
      {{ java_version_result.stderr | trim }}
  debug:
    msg: "{{ msg.split('\r\n')[:-1] }}"
