---
- name: Install Java (Windows)
  win_package:
    path: "{{ java_installers_path_on_target }}\\{{ java_installer_filename }}"
    creates_path: "{{ java_destination_path }}\\{{ java_type_and_version }}"
    state: present
