---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: macos-10.13.5
    box: macos-10.13.5
    memory: 3072
    cpus: 2
provisioner:
  name: ansible
  lint:
    name: ansible-lint
ansible:
  connection_options:
    ansible_user: vagrant
scenario:
  name: macos-vagrant
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    - converge
    - verify
    - destroy
verifier:
  name: testinfra
  options:
    verbose: true
  lint:
    name: flake8
    enabled: false
