---
- name: Check Java cryptography unlimited strength status (Windows)
  win_command: "\"{{ java_destination_parent_path }}\\{{ java_dir_string }}\\bin\\jrunscript.exe\" -e \"exit (println(javax.crypto.Cipher.getMaxAllowedKeyLength('AES') >= 256));\""
  register: unlimited
  changed_when: false

- name: Set unlimited_strength (Windows)
  set_fact:
    unlimited_strength: '{{ unlimited.stdout | trim }}'
