---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: centos7
    image: centos:7
  - name: centos6
    image: centos:6
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: centos-docker
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    - converge
    - verify
    - destroy
verifier:
  name: testinfra
  options:
    verbose: true
  lint:
    name: flake8
    enabled: false
