---
- name: Get directories in java_destination_parent_path (Unix)
  find:
    paths: "{{ java_destination_parent_path }}"
    file_type: directory
    recurse: false
  become: true
  register: found_dirs
