---
- name: Ensure java_installers_path_on_target exists (Unix)
  file:
    path: "{{ java_installers_path_on_target }}"
    state: directory
    mode: 0777
  become: true

- name: Copy JCE archive to target (Unix)
  copy:
    src: "{{ java_installers_path_on_controller }}/{{ jce_archive_name }}"
    dest: "{{ java_installers_path_on_target }}"

- name: Check JCE archive on target (Unix)
  stat:
    path: "{{ java_installers_path_on_target }}/{{ jce_archive_name }}"
  register: archive
  failed_when: archive.stat.exists != true
