---
- name: Get Installed Java Version
  command: "{{ java_destination_path }}/{{ java_type_and_version }}/bin/java -version"
  register: java_version_result

- name: Java Version
  vars:
    msg: |
      {{ java_version_result.stderr | trim }}
  debug:
    msg: "{{ msg.split('\n')[:-1] }}"