---
- name: Select java_version (Debian)
  alternatives:
    name: "{{ item }}"
    link: "/usr/bin/{{ item }}"
    path: "{{ java_path }}/bin/{{ item }}"
    priority: 100
  become: true
  loop: "{{ java_executables|flatten(levels=1) }}"

- name: Set JAVA_HOME (Debian)
  lineinfile:
    dest: "{{ java_environment_file_path }}"
    state: present
    regexp: '^JAVA_HOME'
    line: "JAVA_HOME={{ java_path }}"
  become: true
