---
- name: Select java_version
  win_path:
    elements:
      - "\"{{ java_destination_path }}\\{{ java_type_and_version }}\\bin\""

- name: Set JAVA_HOME
  win_environment:
    state: present
    name: JAVA_HOME
    value: "\"{{ java_destination_path }}\\{{ java_type_and_version }}\""
    level: machine

- name: Get Installed Java Version
  win_command: "\"{{ java_destination_path }}\\{{ java_type_and_version }}\\bin\\java\" -version"
  register: java_version_result

- name: Java Version
  vars:
    msg: |
      {{ java_version_result.stderr | trim }}
  debug:
    msg: "{{ msg.split('\r\n')[:-1] }}"
