---
- name: Create temp Ansible directory (Windows)
  win_file:
    path: "{{ java_installers_path_on_target }}"
    state: directory

- name: Copy installer to target (Windows)
  win_copy:
    src: "{{ java_installers_path_on_controller }}/{{ java_installer_filename }}"
    dest: "{{ java_installers_path_on_target }}\\{{ java_installer_filename }}"

- name: Check for installer (Windows)
  win_stat:
    path: "\"{{ java_installers_path_on_target }}\\{{ java_installer_filename }}\""
  register: installer
  failed_when: installer.stat.exists != true
