---
- name: Ensure crypto.policy for Java is unlimited (Windows)
  win_lineinfile:
    path: "{{ java_security_path }}\\java.security"
    regexp: '^\s*#*\s*crypto.policy=.*$'
    line: 'crypto.policy=unlimited'
