---
- name: Get Installed Java Version (Unix)
  command: java -version
  register: java_version_result

- name: Java Version
  vars:
    msg: |
      {{ java_version_result.stderr | trim }}
  debug:
    msg: "{{ msg.split('\n')[:-1] }}"
