---
- name: Get newest directory
  include_tasks: "{{ os_architecture }}/specific.yml"

- name: Set java_path to most recent directory in java_destination_path
  set_fact:
    java_path: "{{ (found_dirs.files | sort(attribute='mtime') | last).path }}"
