---
- name: Get directories in java_destination_parent_path
  include_tasks: "{{ os_architecture }}/paths.yml"

- name: Set java_path to most recent directory in java_destination_parent_path
  set_fact:
    java_path: "{{ (found_dirs.files | sort(attribute='mtime') | last).path }}"
