---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: ubuntu12
    image: ubuntu:12.04
  - name: ubuntu14
    image: ubuntu:14.04
  - name: ubuntu16
    image: ubuntu:16.04
  - name: ubuntu18
    image: ubuntu:18.04
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: ubuntu-docker
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    - converge
    - verify
    - destroy
verifier:
  name: testinfra
  directory: ../tests/
  options:
    verbose: true
  lint:
    name: flake8
    enabled: false
