---
- debug:
    msg: "Java version: {{ java_version }}"

- name: Define java_version_style
  set_fact:
    java_version_style: |-
      {%- if (java_version|string).split('.')[0]|int > 8 %}
      modern
      {%- else %}
      legacy
      {%- endif %}

- name: Define java_version based on style
  include_tasks: "java_version_style/{{ java_version_style }}.yml"
