---
- name: Include Unix variables
  include_vars: Unix/vars.yml
  when: ansible_os_family != "Windows"

- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}/vars.yml"

# code from https://www.samdarwin.com/ansible-default-vars/
- name: Set facts based on defaults
  set_fact:
    "{{ item[8:] }}": "{{  vars[item[8:]] | default(vars[item]) }}"
  when: item is match("^default_")
  with_items:
    "{{ vars }}"

- name: Define java_version
  include_tasks: java_version.yml

- name: Define java_installer_filename
  include_tasks: "{{ ansible_os_family }}/java_installer_filename.yml"

- name: Define values based on environment variables
  include_tasks: env_vars.yml
