---
- name: Get Installed Java Version (Unix)
  command: java -version
  register: java_version_result
  changed_when: false

- name: Java Version
  vars:
    msg: |
      {{ java_version_result.stderr | trim }}
  debug:
    msg: "{{ msg.split('\n')[:-1] }}"

- name: Warning if not using latest Java version
  vars:
    msg: |
      WARNING: This is not the latest Java version available
      Latest version: {{ latest_java_version }}
  debug:
    msg: "{{ msg.split('\n')[:-1] }}"
  when: latest_java_version != java_version
