---
- name: Create java_destination_parent_path
  file:
    path: "{{ java_destination_parent_path }}"
    state: directory
  become: true

- name: Unarchive Java (RedHat)
  yum:
    name: "{{ java_installers_path_on_target }}/{{ java_installer_filename }}"
    state: present
  become: true
