---
- name: Ensure JCE pre-requisites exist
  include_tasks: "jce/pre-reqs/exist.yml"

- name: Ensure JCE archive has been obtained
  include_tasks: "jce/archive/obtained.yml"

- name: Ensure JCE files are installed
  include_tasks: "jce/files/installed.yml"
