---
- name: Ensure JCE pre-requisites exist
  include_tasks: "jce/pre-reqs/{{ ansible_os_family }}/exist.yml"

- name: Ensure JCE archive has been obtained
  include_tasks: "jce/archive/{{ os_architecture }}/obtained.yml"

- name: Ensure JCE files are installed
  include_tasks: "jce/{{ os_architecture }}/installed.yml"
