---
- name: Get Installed Java Version (Windows)
  win_command: "\"{{ java_destination_parent_path }}\\{{ java_dir_string }}\\bin\\java\" -version"
  register: java_version_result
  changed_when: false

- name: Java Version (Windows)
  vars:
    msg: |
      {{ java_version_result.stderr | trim }}
  debug:
    msg: "{{ msg.split('\r\n')[:-1] }}"

- name: Warning if not using latest Java version (Windows)
  vars:
    msg: |
      WARNING: This is not the latest Java version available
      Latest version: {{ latest_java_version }}
  debug:
    msg: "{{ msg.split('\r\n')[:-1] }}"
  when: latest_java_version != java_version
