- name: Define defaults & variables
  include_tasks: default_vars.yml

- name: Define values based on environment variables
  include_tasks: env_vars.yml

- name: Define latest_java_version using latest available from Oracle
  include_tasks: java_version_from_oracle.yml

- name: Set java_version_style
  set_fact:
    java_version_style: |-
      {%- if (java_version|string).split('.')[0]|int > 8 %}
      modern
      {%- else %}
      legacy
      {%- endif %}

- name: Define java_version and java_crypto based on style
  include_tasks: "java_version_and_crypto/{{ java_version_style }}.yml"

- name: Define OS family specific variable
  include_tasks: "{{ ansible_facts.os_family }}/vars.yml"

- name: Define Linux java_installer_name_parts
  include_tasks: "Linux/java_installer_name_parts.yml"
  when: ansible_facts.os_family not in ['Windows', 'Darwin']

- name: Define OS family specific java_installer_name_parts
  include_tasks: "{{ ansible_facts.os_family }}/java_installer_name_parts.yml"

- name: Set java_installer_filename
  set_fact:
    java_installer_filename: "{{ java_type_string }}-{{ java_version_short_string }}{{ java_installer_suffix }}{{ java_installer_ext }}"

- name: Define java_crypto variables
  include_tasks: "java_crypto/jce_{{ java_version_parts['major'] }}.yml"
  when: java_crypto_style == 'legacy'
